# Generated by Django 5.2.9 on 2025-12-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="email_host_password",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
